### ISSUE TITLE
st_make_valid removed from lwgeom (moved to sf)

### ISSUE THREAD

**Issue by edzer** [r-spatial/lwgeom#52]
This affects the following revdeps, who have been informed:
* `edbuildmapr` (informed by email)
* https://github.com/smwoodman/eSDM/issues/9
* https://github.com/ipeaGIT/gtfs2gps/issues/112
* https://github.com/munterfinger/hereR/issues/38
* https://github.com/uribo/jpndistrict/issues/32
* https://github.com/rCarto/osrm/issues/58
* https://github.com/jlacko/RCzechia/issues/15
* https://github.com/Groupe-ElementR/SpatialPosition/issues/18
* https://github.com/rCarto/tanaka/issues/2
* https://github.com/prioritizr/wdpar/issues/24

**Comment by jlacko** [comment]
I have a question related to this: is there a consensus approach to handling the transition?

When I use `sf::st_make_valid` instead of `lwgeom::st_make_valid` in my package I get an error in some evironments (e.g. Travis) that lwgeom is not available. Apparently sf uses it as a fallback in case of old GEOS; the version on Travis is rather ancient - but Travis is a key tool in CI.

```
Loading required package: sf
Linking to GEOS 3.7.1, GDAL 2.2.2, PROJ 4.9.2
── 1. Error: (unknown) (@test-2-code.R#20)  ────────────────────────────────────
lwgeom required: install that first
```

**Comment by edzer** [comment]
Yes, that is right, and that will remain the case until the GEOS version having st_make_valid has propagated through all distributions. For such cases you can still change the import, but keep `lwgeom` in `Suggests:`.

**Comment by jlacko** [comment]
thank you, `suggests: lwgeom`  has to remain; then all is well...
